from . import utils
from pathlib import Path
from typing import Any, BinaryIO, Iterable, Optional

def choose_iter(name: Any, json_format: Optional[utils.JsonFormat]) -> Any: ...
def load(fp: BinaryIO, *, json_format: Optional[utils.JsonFormat]=...) -> Iterable: ...
def load_from_file(file_name: Path, *, json_format: Optional[utils.JsonFormat]=..., file_mode: str=..., use_stdin_as_default: bool=...) -> Iterable: ...
def dump(in_iter_: Any, fp: BinaryIO, *, json_format: Optional[utils.JsonFormat]=...) -> Any: ...
def dump_to_file(in_iter_: Any, file_name: Path, *, json_format: Optional[utils.JsonFormat]=..., file_mode: str=..., use_stdout_as_default: bool=..., use_stderr_as_default: bool=...) -> Any: ...
def sink(fp: BinaryIO, *, json_format: Optional[utils.JsonFormat]=...) -> Any: ...
def sink_from_file(file_name: Path, *, json_format: Optional[utils.JsonFormat]=..., file_mode: str=..., use_stdout_as_default: bool=..., use_stderr_as_default: bool=...) -> Any: ...
