language: python
dist: xenial
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"
  - "nightly"
env:
  - JSONLIB=orjson
  - JSONLIB=ujson
  - JSONLIB=json
matrix:
  allow_failures:
    - python: 3.9-dev
    - python: nightly

install:
  - make install-dev
  - pip install codecov
  - test $JSONLIB = "orjson" && .venv/bin/pip install orjson || echo "skip"
  - test $JSONLIB = "ujson" && .venv/bin/pip install ujson || echo "skip"
script: make test-w-coverage
after_success:
  - codecov
notifications:
  email:
    on_success: change
    on_failure: always
