language: python
dist: xenial
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"
  - "nightly"
env:
  - JSONLIB=orjson
  - JSONLIB=ujson
  - JSONLIB=json
matrix:
  allow_failures:
    - python: 3.9-dev
    - python: nightly
jobs:
  include:
    - stage: Install dependencies
      script:
        - make install-dev
        - pip install codecov
    - script: .venv/bin/pip install orjson
      env: JSONLIB=orjson
    - script: .venv/bin/pip install ujson
      env: JSONLIB=ujson
    - stage: Test
      script: make test-w-coverage
after_success:
  - codecov
notifications:
  email:
    on_success: change
    on_failure: always
