name: check

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

permissions:
  contents: read

env:
  MINIMUM_PYTHON_VERSION: "3.9"
  UV_VERSION: "0.8.13"

# If new code is pushed to a PR branch, then cancel in progress workflows for that PR. Ensures that
# we don't waste CI time, and returns results quicker https://github.com/jonhoo/rust-ci-conf/pull/5
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  fmt:
    runs-on: ubuntu-latest
    name: ubuntu / 3.9 / fmt
    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v5.0.0
        with:
          persist-credentials: false
          submodules: true

      - name: Set up the python ${{ env.MINIMUM_PYTHON_VERSION }}
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        id: setup-python
        with:
          python-version: ${{ env.MINIMUM_PYTHON_VERSION }}

      #----------------------------------------------
      #  -----  setup uv and load cache   -----
      #----------------------------------------------
      - name: Set up uv
        uses: astral-sh/setup-uv@2841f9f5c1f3a4d2fe660cb20a8910794bac0423
        with:
          version: ${{ env.UV_VERSION }}
          enable-cache: true

      - name: Install dependencies
        run: make install-dev

      - name: check formatting
        run: make check-fmt

  lint:
    runs-on: ubuntu-latest
    name: ubuntu / 3.9 / lint
    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v5.0.0
        with:
          persist-credentials: false
          submodules: true
      - name: Set up the python ${{ env.MINIMUM_PYTHON_VERSION }}
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        id: setup-python
        with:
          python-version: ${{ env.MINIMUM_PYTHON_VERSION }}

      #----------------------------------------------
      #  -----  setup uv and load cache   -----
      #----------------------------------------------
      - name: Set up uv
        uses: astral-sh/setup-uv@2841f9f5c1f3a4d2fe660cb20a8910794bac0423
        with:
          version: ${{ env.UV_VERSION }}
          enable-cache: true

      - name: Install dependencies
        run: make install-dev

      - name: lint code
        run: make lint

  type-check:
    runs-on: ubuntu-latest
    name: ubuntu / 3.9 / type-check
    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v5.0.0
        with:
          persist-credentials: false
          submodules: true
      - name: Set up the python ${{ env.MINIMUM_PYTHON_VERSION }}
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        id: setup-python
        with:
          python-version: ${{ env.MINIMUM_PYTHON_VERSION }}

      #----------------------------------------------
      #  -----  setup uv and load cache   -----
      #----------------------------------------------
      - name: Set up uv
        uses: astral-sh/setup-uv@2841f9f5c1f3a4d2fe660cb20a8910794bac0423
        with:
          version: ${{ env.UV_VERSION }}
          enable-cache: true

      - name: Install dependencies
        run: make install-dev

      - name: type-check code
        run: make type-check

  # https://github.com/marketplace/actions/alls-green#why used for branch protection checks
  check-check:
    if: always()
    needs:
      - fmt
      - lint
      - type-check
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
