name: release

on:
  push:
    branches:
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
permissions:
  contents: read

env:
  MINIMUM_PYTHON_VERSION: "3.9"
  UV_VERSION: "0.6.17"

jobs:
  build:
    # This action builds distribution files for upload to PyPI

    name: ubuntu / 3.9 / build
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v5.0.0
        with:
          persist-credentials: false
          submodules: true

      #----------------------------------------------
      #  -----  setup python   -----
      #----------------------------------------------
      - name: Set up the environment
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        id: setup-python
        with:
          python-version: ${{ env.MINIMUM_PYTHON_VERSION }}

      #----------------------------------------------
      #  -----  setup uv and load cache   -----
      #----------------------------------------------
      - name: Set up uv
        uses: astral-sh/setup-uv@c0e7e93474eb09a343746f2a2742979d0cba523c # v6.5.0
        with:
          version: ${{ env.UV_VERSION }}
          enable-cache: true

      #----------------------------------------------
      #  -----  build distribution -----
      #----------------------------------------------
      - name: Build distribution
        run: make build

      #----------------------------------------------
      #  -----  upload artifacts  -----
      #----------------------------------------------
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: pypi_files
          path: dist

  test-build:
    # This action runs the test suite on the built artifact in the `build` action.
    # The default is to run this in ubuntu, macos and windows

    name: ${{ matrix.os }} / 3.9 / test built artifact
    needs: [build]

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu
          - macos
          - windows

    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v5.0.0
        with:
          persist-credentials: false
          submodules: true

      - name: set up python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: ${{ env.MINIMUM_PYTHON_VERSION }}

      - name: get dist artifacts
        uses: actions/download-artifact@de96f4613b77ec03b5cf633e7c350c32bd3c5660 # v5.0.0
        with:
          name: pypi_files
          path: dist

      - run: rm -r <INSERT PROJECT SRC>
      - run: pip install typing-extensions
      - run: pip install -r tests/requirements-testing.lock
      - run: pip install <INSERT PROJECT NAME> --no-index --no-deps --find-links dist --force-reinstall
      - run: pytest

  # https://github.com/marketplace/actions/alls-green#why used for branch protection checks
  release-check:
    if: always()
    needs:
      - build
      - test-build
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
          # allowed-failures: coverage

  publish:
    # This action publishes the built and tested artifact to PyPI, but only on a tag

    needs:
      - test-build
    if: success() && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    environment: release
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v5.0.0
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Set up Python ${{ env.MINIMUM_PYTHON_VERSION }}
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: ${{ env.MINIMUM_PYTHON_VERSION }}
      - name: get dist artifacts
        uses: actions/download-artifact@de96f4613b77ec03b5cf633e7c350c32bd3c5660 # v5.0.0
        with:
          name: pypi_files
          path: dist

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc # v1.12.4
