# Run scheduled (rolling) jobs on a nightly basis, as your crate may break independently of any
# given PR. E.g., updates to rust nightly and updates to this crates dependencies. See check.yml for
# information about how the concurrency cancellation and workflow triggering works
permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "7 7 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

name: rolling

env:
  UV_VERSION: "0.8.13"

jobs:
  # https://twitter.com/mycoliza/status/1571295690063753218
  nightly:
    runs-on: ubuntu-latest
    name: ubuntu / 3.14-dev
    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v5.0.0
        with:
          persist-credentials: false
          submodules: true

      - name: Set up uv
        uses: astral-sh/setup-uv@2841f9f5c1f3a4d2fe660cb20a8910794bac0423
        with:
          version: ${{ env.UV_VERSION }}
          enable-cache: true

      - name: Install python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: "3.14-dev"

      - run: python --version

      - name: uv lock
        if: hashFiles('uv.lock') == ''
        run: uv lock

      - name: uv sync --dev
        run: uv sync --dev --all-packages --all-extras

      - name: make test
        run: make test

  # https://twitter.com/alcuadrado/status/1571291687837732873
  update:
    # This action checks that updating the dependencies of this crate to the latest available that
    # satisfy the versions in pyproject.toml does not break this crate. This is important as consumers
    # of this crate will generally use the latest available crates. This is subject to the standard
    # Cargo semver rules (i.e cargo does not update to a new major version unless explicitly told
    # to).
    runs-on: ubuntu-latest
    name: ubuntu / 3.13 / updates work
    # There's no point running this if no uv.lock was checked in in the first place, since we'd
    # just redo what happened in the regular test job. Unfortunately, hashFiles only works in if on
    # steps, so we repeat it.
    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v5.0.0
        with:
          persist-credentials: false
          submodules: true

      - name: Set up uv
        if: hashFiles('uv.lock') != ''
        uses: astral-sh/setup-uv@2841f9f5c1f3a4d2fe660cb20a8910794bac0423
        with:
          version: ${{ env.UV_VERSION }}
          enable-cache: true

      - name: Install 3.13
        if: hashFiles('uv.lock') != ''
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: "3.13"

      - name: uv sync --dev --upgrade
        if: hashFiles('uv.lock') != ''
        run: uv sync --dev --upgrade --all-packages --all-extras

      - name: make test
        if: hashFiles('uv.lock') != ''
        run: make test
